import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/Shared/theme-provider';
import Navbar from '@/components/Shared/Navbar';
import GlobalStatistics from '@/components/Shared/Navbar/GlobalStatistics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Coin Watch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar globalStatistics={<GlobalStatistics />} />
          <main className="px-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
