name: Release

on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        env:
          GECKO_API_URL: ${{secrets.GECKO_API_URL}}
      - run: bun install
      - run: bun run build
      - run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
